<?php

/*
 * AHnames implementation of HiPanel
 *
 * @link      https://ahnames.com/
 * @package   hipanel
 * @license   proprietary
 * @copyright Copyright (c) 2015-2016, AHnames (https://ahnames.com/)
 */

namespace ahnames\hipanel\tests\unit\assets;

use ahnames\hipanel\assets\ProjectAsset;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-05-14 at 05:02:19.
 */
class ProjectAssetTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var ProjectAsset
     */
    protected $object;

    protected function setUp()
    {
        $this->object = new ProjectAsset;
    }

    protected function tearDown()
    {
    }

    public function testConstruct()
    {
        $this->assertInstanceOf(ProjectAsset::class, $this->object);
    }
}
