package:
    name:           hipanel
    namespace:      ahnames\hipanel
    headline:       AHnames HiPanel
    title:          AHnames implementation of HiPanel
    type:           project
    homepage:       https://ahnames.com/
    keywords:       ahnames, hipanel, control panel, hosting, domains
    year:           2015
    description:    |
        [HiPanel](http://hipanel.com) is next generation control panel for hosting, domains and more.
        This package is HiPanel build for [AHnames](https://ahnames.com) domain registrator.

require:
    ahnames/hidev-config:       "*"
    hiqdev/hidev-config-php:    "*"
