package:
    type:           project
    name:           hipanel
    title:          AHnames implementation of HiPanel
    headline:       AHnames HiPanel
    homepage:       https://ahnames.com/
    keywords:       ahnames, hipanel, control panel, hosting, domains
    namespace:      ahnames\hipanel
    description:    |
        [HiPanel](http://hipanel.com) is next generation control panel for hosting, domains and more.

        This package is HiPanel build for [AHnames](https://ahnames.com) domain registrator.

